### ISSUE TITLE
Doesn't compile with Android Studio 3.3.2

### ISSUE THREAD

**Issue by rafoid** [sujitpanda/Google-Cloud-Speech-API#2]
Using 

```
android {
    compileSdkVersion 28
...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

in my project. Attempting to build it, gives me the following compilation error:

```
AGPBI: {"kind":"error","text":"Program type already present: com.google.protobuf.AbstractMessageLite","sources":[{}],"tool":"D8"}
:app:transformDexArchiveWithExternalLibsDexMergerForDebug (Thread[Task worker for ':',5,main]) completed. Took 1.069 secs.
:app:buildInfoGeneratorDebug (Thread[Task worker for ':',5,main]) started.
> Task :app:buildInfoGeneratorDebug
Task ':app:buildInfoGeneratorDebug' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:app:buildInfoGeneratorDebug (Thread[Task worker for ':',5,main]) completed. Took 0.002 secs.
FAILURE: Build failed with an exception.
```

**Comment by rafoid** [comment]
If I comment out the following lines in build.gradle (Module: app):

```
    // gRPC
    implementation "io.grpc:grpc-okhttp:$grpcVersion"
    implementation "io.grpc:grpc-stub:$grpcVersion"
    implementation 'javax.annotation:javax.annotation-api:1.2'
    //implementation "io.grpc:grpc-protobuf-lite:$grpcVersion"
    //protobuf 'com.google.protobuf:protobuf-java:3.4.0'
```

then I can build the app. However, when executing it, with onVoiceStart() calling mSpeechService.startRecognizing(), it tells me there is no method build()!?!? Below is the error message and the code which it complains about:

`    java.lang.NoSuchMethodError: No virtual method build()Lcom/google/protobuf/GeneratedMessageLite; in class Lcom/google/cloud/speech/v1/RecognitionConfig$Builder; or its super classes (declaration of 'com.google.cloud.speech.v1.RecognitionConfig$Builder' appears in /data/app/com.example.commit2memory-vYoJLO9qrS4J1NWNBTWITA==/split_lib_dependencies_apk.apk)
`

```
    public void startRecognizing(int sampleRate) {
        if (mApi == null) {
            Log.w(TAG, "API not ready. Ignoring the request.");
            return;
        }
        // Configure the API
        mRequestObserver = mApi.streamingRecognize(mResponseObserver);
        mRequestObserver.onNext(StreamingRecognizeRequest.newBuilder()
                .setStreamingConfig(StreamingRecognitionConfig.newBuilder()
                        .setConfig(RecognitionConfig.newBuilder()
                                .setLanguageCode(getDefaultLanguageCode())
                                .setEncoding(RecognitionConfig.AudioEncoding.LINEAR16)
                                .setSampleRateHertz(sampleRate)
                                .build())
                        .setInterimResults(true)
                        .setSingleUtterance(true)
                        .build())
                .build());
    }
```

The build() it can't find is related to RecognitionConfig.newBuilder().build() method. Any suggestions?
